=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica01/mensaje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mail">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fecha" type="xs:date"/>
				<xs:element name="remitente" type="xs:string"/>
				<xs:element name="destinatario">					
					<xs:complexType>
						<xs:sequence>
							<xs:element name="correo" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="asunto" type="xs:string" minOccurs="0"/>
				<xs:element name="mensaje" type="xs:string" minOccurs="0"/>
				<xs:element name="adjuntos" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="image" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tipo" type="xs:string"/>
										<xs:element name="nombre" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica01/mensaje.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mail [
	<!ELEMENT fecha (#PCDATA)>
	<!ELEMENT remitente (#PCDATA)>
	<!ELEMENT correo (#PCDATA)>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT mensaje (#PCDATA)>
	<!ELEMENT tipo (#PCDATA)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT destinatario (correo+)>
	<!ELEMENT image (tipo, nombre)>
	<!ELEMENT adjuntos (image+)>
	<!ELEMENT mail (fecha, remitente, destinatario, asunto?, mensaje, adjuntos?)>
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED
				   xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]> 
<mail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="mensaje.xsd">
	<fecha>2020-06-18</fecha>
	<remitente>moiroyale10@gmail.com</remitente>
	<destinatario>
		<correo>moisesa.jcyl.es</correo>
		<correo>amorrodriguez.jcyl.es</correo>
	</destinatario>
	<asunto>Fiesta</asunto>
	<mensaje>Fiesta final de las clases jeje</mensaje>
	<adjuntos>
		<image>
			<tipo>image/png</tipo>
			<nombre>foto1.png</nombre>
		</image>
		<image>
			<tipo>image/png</tipo>
			<nombre>foto2.png</nombre>
		</image>
	</adjuntos>
</mail>
