=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica04/xml04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mail">	
		<xs:complexType>
			<xs:sequence>	
			
				<xs:element name="remitente" maxOccurs="1"/>
				<xs:element name="destinatario">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="correo" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="asunto" minOccurs="1" type="xs:string"/>
				<xs:element name="mensaje" minOccurs="1"/>
				<xs:element name="adjuntos" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="image" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="type">
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:pattern value="imagepng|imagejpg|imageico"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>							
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		<xs:attribute name="fecha" type="xs:date"/> 
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica04/xml04.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE mail [
	<!ELEMENT remitente (#PCDATA)>
	<!ELEMENT correo (#PCDATA)>
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT mensaje (#PCDATA)>
	<!ELEMENT image (#PCDATA)>
	<!ELEMENT destinatario (correo+)>
	<!ELEMENT adjuntos (image*)>
	<!ELEMENT mail (remitente, destinatario, asunto?, mensaje, adjuntos?)>
	<!ATTLIST mail fecha CDATA #REQUIRED>
	<!ATTLIST image type (imagepng|imagejpg|imageico) #REQUIRED>
	<!ATTLIST mail xmlns:xsi CDATA #IMPLIED
				   xsi:noNamespaceSchemaLocation CDATA #IMPLIED> 
]>
<mail fecha="2020-01-14" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml04.xsd">
	<remitente>moisesroyale10@gmail.com</remitente>
	<destinatario>
		<correo>moisesa.jcyl.es</correo>
		<correo>amorrodriguez.jcyl.es</correo>
	</destinatario>
	<asunto>Fiesta de fin de curso</asunto>
	<mensaje>Ultramix 2020</mensaje>
	<adjuntos>
		<image type="imagepng">foto1.png</image>
		<image type="imagejpg">foto2.jpg</image>
		<image type="imageico">foto3.ico</image>
	</adjuntos>
</mail>
