<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE historia[
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT fecha EMPTY>
	<!ELEMENT hechos_historicos (descripcion+, fecha)>
	<!ELEMENT historia (hechos_historicos+)>
	<!ATTLIST fecha dia CDATA #REQUIRED>
	<!ATTLIST fecha mes CDATA #REQUIRED>
	<!ATTLIST fecha anyo CDATA #REQUIRED>
]>
<historia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml06.xsd">
	<hechos_historicos>
		<descripcion>Se funda Youtube</descripcion>
		<fecha dia="15" mes="02" anyo="2005"/>
	</hechos_historicos>
	<hechos_historicos>
		<descripcion>Se funda Google</descripcion>
		<fecha dia="4" mes="09" anyo="1998"/>
	</hechos_historicos>
	<hechos_historicos>
		<descripcion>Se funda Facebook</descripcion>
		<fecha dia="4" mes="02" anyo="2004"/>
	</hechos_historicos>
</historia>