=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica03/xml03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="historia">
		<xs:complexType>
			<xs:sequence>	
				<xs:element name="hechos_historicos" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="descripcion" type="xs:string"/>
							<xs:element name="fecha" minOccurs="1" maxOccurs="2">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dia" type="xs:integer"/>
										<xs:element name="mes" type="xs:integer"/>
										<xs:element name="anyo" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica03/xml03.xml
<historia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml03.xsd">
	<hechos_historicos>
		<descripcion>Se funda Youtube</descripcion>
		<fecha>
			<dia>15</dia>
			<mes>2</mes>
			<anyo>2005</anyo>
		</fecha>
	</hechos_historicos>
	<hechos_historicos>
		<descripcion>Se funda Google</descripcion>
		<fecha>
			<dia>4</dia>
			<mes>9</mes>
			<anyo>1998</anyo>
		</fecha>
	</hechos_historicos>
	<hechos_historicos>
		<descripcion>Se funda Facebook</descripcion>
		<fecha>
			<dia>4</dia>
			<mes>2</mes>
			<anyo>2004</anyo>
		</fecha>
	</hechos_historicos>
</historia>
