<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta[
	<!ELEMENT receta (nombre, descripcion*, tiempo, ingredientes, instrucciones*)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT tiempo (#PCDATA)>
	<!ELEMENT ingredientes (ingrediente+)>
	<!ELEMENT instrucciones (paso+)>
	<!ELEMENT ingrediente (nombre, cantidad?)>
	<!ELEMENT paso (#PCDATA)>
	<!ELEMENT cantidad (#PCDATA)>
	<!ATTLIST receta plato (primero|segundo|postre) #REQUIRED>
	<!ATTLIST tiempo preparacion CDATA #REQUIRED>
	<!ATTLIST tiempo coccion CDATA #IMPLIED>
	<!ATTLIST cantidad unidad (gramos|pizca|mililitros|cucharada|chorro) #IMPLIED>
]>
<receta plato="primero" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="receta.xsd">
	<nombre>Risotto Milanesa</nombre>
	<tiempo preparacion="20" coccion="20"/>
	<ingredientes>
		<ingrediente>
			<nombre>Arroz</nombre>
			<cantidad unidad="gramos">500</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Cebolla</nombre>
			<cantidad>1</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Azafrán</nombre>
			<cantidad unidad="pizca">1</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Queso Parmesano</nombre>
			<cantidad unidad="gramos">100</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Mantequilla</nombre>
			<cantidad unidad="gramos">100</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Sal</nombre>
		</ingrediente>
		<ingrediente>
			<nombre>Pimienta</nombre>
		</ingrediente>
		<ingrediente>
			<nombre>Caldo</nombre>
			<cantidad unidad="mililitros">1000</cantidad>
		</ingrediente>
		<ingrediente>
			<nombre>Vino Blanco</nombre>
			<cantidad unidad="chorro">1</cantidad>
		</ingrediente>
	</ingredientes>
	<instrucciones>
		<paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla.</paso>
		<paso>Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca.</paso>
		<paso>A continuación, incorporamos el arróz, lo sofreímos un poco.</paso>
		<paso>Vamos añadiendo el caldo caliente poco a poco mientras removemos.</paso>
		<paso>Salpimentamos.</paso>
		<paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso.</paso>
		<paso>Servimos enseguida.</paso>
	</instrucciones>
</receta>