=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica02/xml02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mundo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="continente" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombrecontinente" type="xs:string"/>
							<xs:element name="pais" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="nombrepais" type="xs:string"/>
										<xs:element name="capital" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica02/xml02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="xml02.xsd">
	<continente>
		<nombrecontinente>Europa</nombrecontinente>
		<pais>
			<nombrepais>Alemania</nombrepais>
			<capital>Berlin</capital>
		</pais>
	</continente>
	<continente>
		<nombrecontinente>America</nombrecontinente>
		<pais>
			<nombrepais>Argentina</nombrepais>
			<capital>Buenos Aires</capital>
		</pais>
		<pais>
			<nombrepais>Bahamas</nombrepais>
			<capital>Nassau</capital>
		</pais>
	</continente>
	<continente>
		<nombrecontinente>Asia</nombrecontinente>
		<pais>
			<nombrepais>Afganistan</nombrepais>
			<capital>Kabul</capital>
		</pais>
		<pais>
			<nombrepais>Arabia Saudita</nombrepais>
			<capital>Riad</capital>
		</pais>
	</continente>
</mundo>
