=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica15/equipos-de-futbol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="futbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="equipo" maxOccurs="20">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"/>
							<xs:element name="ciudad" type="xs:string"/>
							<xs:element name="entrenador" type="xs:string"/>
							<xs:element name="jugadores">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="jugador" maxOccurs="22">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="nombre" type="xs:string"/>
													<xs:element name="nacionalidad" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="posicion" type="xs:string"/>
												<xs:attribute name="dorsal" type="xs:byte">
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== moisesdcsauces/Proyecto1920_LMSGI_MADC/1920_LMSGI_MADC/practicas/xml/practica15/equipos-de-futbol.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<futbol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="equipos-de-futbol.xsd">
	<equipo>
		<nombre>Liverpool</nombre>
		<ciudad>Liverpool</ciudad>
		<entrenador>Jurgen Klop</entrenador>
		<jugadores>
			<jugador posicion="portero" dorsal="1">
				<nombre>Alisson</nombre>
				<nacionalidad>Brasile√±o</nacionalidad>
			</jugador>
			<jugador posicion="Delantero" dorsal="10">
				<nombre>Sadio Mane</nombre>
				<nacionalidad>Senegales</nacionalidad>
			</jugador>
		</jugadores>
	</equipo>
</futbol>
