<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE Company [
	<!ELEMENT Company (Employee*)>
	<!ELEMENT Employee (FirstName, LastName, ContactNo, Email*, Address)>
	<!ELEMENT FirstName (#PCDATA)>
	<!ELEMENT LastName (#PCDATA)>
	<!ELEMENT ContactNo (#PCDATA)>
	<!ELEMENT Email (#PCDATA)>
	<!ELEMENT Address (City, State, Zip)>
	<!ELEMENT City (#PCDATA)>
	<!ELEMENT State (#PCDATA)>
	<!ELEMENT Zip (#PCDATA)>
]>


<Company>
	<Employee>
		<FirstName>Mois√©s</FirstName>
		<LastName>Alberto</LastName>
		<ContactNo>+639778899</ContactNo>
		<Email>moi@gmail.com</Email>
		<Address>
			<City>Benavente</City>
			<State>Zamora</State>
			<Zip>49600</Zip>
		</Address>
	</Employee>
</Company>